from decimal import Decimal
from sqlalchemy import String, Numeric
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column
from app.models.base import Base


class SearchIndex(Base):
    __tablename__ = "search_index"

    symbol: Mapped[str] = mapped_column(
        String(20),
        primary_key=True
    )
    name: Mapped[str] = mapped_column(
        String(200),
        nullable=False
    )
    sector: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="Other",
        server_default="Other"
    )
    type: Mapped[str] = mapped_column(
        String(20),
        nullable=False
    )
    market_cap: Mapped[Decimal | None] = mapped_column(
        Numeric(16, 2),
        nullable=True
    )
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR,
        nullable=True,
        deferred=True  # Usually retrieved only when searching, generated by DB
    )
